[package]
name = "egui-temp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.18.0", features = ["dark-light"] }
egui = "0.18.1"
